//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEscuela
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Materia
    {
        public int idMateria { get; set; }
        public string Mateia { get; set; }
        public string Descripcion { get; set; }
    }
}
