//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEscuela
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Materia
    {
        public int idMateria { get; set; }
        public string Mateia { get; set; }
        public string Descripcion { get; set; }
    }

    public MetodoDePiojo{
		println(pendejos);
	}
}
